[fix](regression) fix case (#5115)
/home/work/unlimit_teamcity/TeamCity/Agents/20251011143603agent_172.16.0.199_1/work/4824d5e564152873/regression-test/data/load_p0/stream_load/empty_field_as_null.csv
2025-10-11 20:21:04.472 INFO [suite-thread-16]
(StreamLoadAction.groovy:434) - failed to waitForPublishOrFailure.
response: null
java.lang.IllegalArgumentException: Text must not be null or empty